import { Shell } from "../components/Shell.js";
import { getSession,startSession,answer,move,finish } from "../services/objectiveQuiz.js";
import { toggleFavorite,isFavorite } from "../services/learning.js";
import { getSettings } from "../services/settings.js";
let speaking=false;
function speak(text){speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); const s=getSettings(); u.lang=s.voiceLang;u.rate=s.voiceRate;speechSynthesis.speak(u)}
export function ObjectiveQuiz(module){let s=getSession(module)||startSession(module);const q=s.questions[s.index],answered=q.userAnswer!==undefined;window.objAnswer=(m,i)=>{answer(m,i);renderApp()};window.objMove=(m,i)=>{move(m,i);speechSynthesis.cancel();renderApp()};window.objFav=(m,id)=>{const ss=getSession(m);toggleFavorite(ss.questions[ss.index],m);renderApp()};window.objSpeak=t=>speak(decodeURIComponent(t));window.objFinish=m=>{const r=finish(m);localStorage.setItem('tefaq-result',JSON.stringify(r));localStorage.setItem('tefaq-result-module',m);goPage('result')}; const text=module==='co'?q.transcript:q.text;
 return Shell(`<main class="page"><div class="quiz-head"><button class="back" onclick="goPage('${module}')">← Exit</button><b>${module.toUpperCase()} · ${s.mode}</b><span>${s.index+1}/${s.questions.length}</span></div><div class="progress"><i style="width:${((s.index+1)/s.questions.length)*100}%"></i></div><div class="palette">${s.questions.map((x,i)=>`<button class="${i===s.index?'current':x.userAnswer===undefined?'':x.userAnswer===x.answer?'ok':'bad'}" onclick="objMove('${module}',${i})">${i+1}</button>`).join('')}</div>
 <section class="card question-card">${module==='co'?`<button onclick="objSpeak('${encodeURIComponent(text)}')">🔊 Play audio</button>`:`<div class="reading">${text}</div>`}<h2>${q.question}</h2><div class="choices">${q.choices.map((c,i)=>`<button ${answered?'disabled':''} class="${answered?(i===q.answer?'correct':i===q.userAnswer?'wrong':''):''}" onclick="objAnswer('${module}',${i})">${String.fromCharCode(65+i)}. ${c}</button>`).join('')}</div>${answered&&s.mode==='practice'?`<div class="feedback"><b>${q.userAnswer===q.answer?'✅ Correct':'❌ Incorrect'}</b><p>${q.explanation||''}</p></div>`:''}</section>
 <div class="actions"><button onclick="objFav('${module}',${q.id})">${isFavorite(q.id,module)?'⭐ Saved':'☆ Favorite'}</button>${s.index>0?`<button onclick="objMove('${module}',${s.index-1})">← Previous</button>`:''}${s.index<s.questions.length-1?`<button onclick="objMove('${module}',${s.index+1})">Next →</button>`:`<button onclick="objFinish('${module}')">Finish</button>`}</div></main>`)}
